Добавлены скрипты для отрисовки карточек товара и показа модальных окон
eimwe/Kolesa-Upgrade-FE-2021 pull request #5
Opened 2021-10-11 11:15 UTC by eimwe

Домашнее задание №5 выполнено

2021-10-11 11:24 UTC, kerim1505k commented on src/js/catalog.js
> +}
Можно сразу return document.querySelectorAll('.shop-card');

2021-10-11 11:26 UTC, kerim1505k commented on src/js/catalog.js
> +    cardContainer.appendChild(customizedCard);
Нужна проверка на cardContainer

Есть shorthand проверки

```
cardContainer?.appendChild(customizedCard);

```

2021-10-11 11:30 UTC, kerim1505k commented on src/js/catalog.js
> +            const clickedCard = event.target;
Тут же можно сразу напрямую использовать id из card.dataset

2021-10-11 11:32 UTC, kerim1505k commented on src/js/catalog.js
> +const renderOrderModals = (card, id) => {
Тут необязательно перекидывать постоянно общий массив "everything" с товарами. Он у тебя объявлен глобально, можешь просто заюзать его здесь, никаких модификаций перед попаданием сюда он не проходит, поэтому нет смысла передавать его как параметр.

2021-10-11 11:33 UTC, kerim1505k commented on src/js/catalog.js
> +    const customizedOrderModal = customizeOrderModalTemplate(title, price, details, fullsized, thumbs);
Нужны проверки на передаваемые данные. В реальных проектах чего-то может и не быть.

2021-10-11 11:34 UTC, kerim1505k commented on src/js/catalog.js
> +    modalCloseButton.addEventListener('click', () => {
Проверка на modalCloseButton

2021-10-11 11:35 UTC, kerim1505k commented on src/js/catalog.js
> +    const orderModal = orderModalTemplate.content.firstElementChild.cloneNode(true);
Проверка на orderModalTemplate

2021-10-11 11:35 UTC, kerim1505k commented on src/js/catalog.js
> +    const fullsizedImgWrapper = orderModal.querySelector('.gallery__fullsize');
Проверки на orderModal

2021-10-11 11:38 UTC, kerim1505k commented on src/js/catalog.js
> +    fullsized.forEach((fullImage) => {
Очень похожий друг на друга код с 49 по 73 строку, сможешь объединить в функцию?

2021-10-11 11:49 UTC, kerim1505k requested changes
Нужны проверки на элементы, которые берешь через querySelector и на передаваемые в функции параметры. Замоканные массивы статичны и в них можно быть уверенными, но в реальных проектах данные с бэкенда бывают разными, поэтому дополнительные проверки на их наличие, либо присвоение параметрам дефолтных значений является обязательным, чтобы работа скрипта не обвалилась.

2021-10-11 14:50 UTC, eimwe commented on src/js/catalog.js
> +}
"+" Исправлено

2021-10-11 15:08 UTC, eimwe commented on src/js/catalog.js
> +    fullsized.forEach((fullImage) => {
"+" Исправил. Объединил в функцию addGalleryImages с всеми параметрами, необходимыми для корректной вставки как тамбнейлов, так и полноразмерных фото

2021-10-11 15:26 UTC, eimwe commented on src/js/catalog.js
> +            const clickedCard = event.target;
"+" Исправлено

2021-10-11 15:30 UTC, eimwe commented on src/js/catalog.js
> +const renderOrderModals = (card, id) => {
"+" Исправлено

2021-10-11 18:08 UTC, eimwe commented on src/js/catalog.js
> +    const customizedOrderModal = customizeOrderModalTemplate(title, price, details, fullsized, thumbs);
Похоже, что я не понимаю, как мне следует проверять данные. Я написал функцию проверки для параметров, передаваемых в функцию `customizeOrderModalTemplate`:
```
const testModalRenderingParams = (...args) => {
  if (Array.isArray(args)) {
      return true;
  }

  args[0] = everything[cardId].title;
  args[1] = everything[cardId].price;
  args[2] = everything[cardId].details;
  args[3] = everything[cardId].fullsized;
  args[4] = everything[cardId].thumbs;

  return args;
};
```
Но я затрудняюсь ответить, правильно ли я её написал и как мне её применить :confused:

2021-10-11 18:13 UTC, eimwe commented on src/js/catalog.js
> +    cardContainer.appendChild(customizedCard);
"+" Исправлено

2021-10-11 18:14 UTC, eimwe commented on src/js/catalog.js
> +    modalCloseButton.addEventListener('click', () => {
"+" Исправлено

2021-10-11 18:17 UTC, eimwe commented on src/js/catalog.js
> +    const orderModal = orderModalTemplate.content.firstElementChild.cloneNode(true);
"+" Исправлено
UPD: заметил, что линтер ругается каждый раз, когда я проставляю оператор `?`. Причем, при добавлении нового аналогичного оператора в другой строке, с прежней строки ошибка исчезает. исполнению скрипта это не мешает. Просто мне стало интересно, это ожидаемое поведение линтера или я как-то неправильно проставляю символ `?` Например, линтер подсвечивает ошибкой эту строку:
`cardTemplate?.content.firstElementChild.cloneNode(true);`

2021-10-11 18:19 UTC, eimwe commented on src/js/catalog.js
> +    const fullsizedImgWrapper = orderModal.querySelector('.gallery__fullsize');
"+" Исправлено

2021-10-12 03:37 UTC, eimwe commented on src/js/catalog.js
> +    const orderModal = orderModalTemplate.content.firstElementChild.cloneNode(true);
UPD 2021-01-12: проблема с линтером больше неактуальна, перезапуск IDE все вылечил

2021-10-12 04:09 UTC, eimwe commented on src/js/catalog.js
> +    const customizedOrderModal = customizeOrderModalTemplate(title, price, details, fullsized, thumbs);
"+" Исправлено. Добавил дефолтные значения для параметров на этапе дестрктуризации

2021-10-12 04:31 UTC, kerim1505k approved these changes

2021-10-12 04:34 UTC, merged